# Should occur every push to main and every pull request to main
name: Test Java Versions and Upload Jar
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Java 8 (Eclipse Temurin) Setup
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "8"
      - name: Java 8 (Eclipse Temurin) Maven Cycle
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
      - name: Java 11 (Microsoft OpenJDK) Setup
        uses: actions/setup-java@v3
        with:
          distribution: "microsoft"
          java-version: "11"
      - name: Java 11 (Microsoft OpenJDK) Maven Cycle
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
      - name: Java 17 (Amazon Corretto OpenJDK) Setup
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
      - name: Java 17 (Amazon Corretto OpenJDK) Maven Cycle
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
      - name: Java 19 (Oracle JDK) Setup
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "19"
      - name: Java 19 (Oracle JDK) Maven Cycle
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
      - name: Java Deployment JDK Setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{vars.JAVA_NUM}}
          distribution: ${{vars.JAVA_TYPE}}
          cache: maven
      - name: Java Deployment JDK Maven Cycle
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
      - name: Remove old jars, add new jar, commit, and push
        run: |
          rm *.jar
          cp target/*.jar .
          git add .
          git config --global user.email "hdavis13@cub.uca.edu"
          git config --global user.name "holden-davis-uca"
          git commit -m "AUTO: Committing jar"
          git push