# Should occur upon the creation of a release
name: Build and Publish Jar to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{vars.JAVA_NUM}}
          distribution: ${{vars.JAVA_TYPE}}
      - name: Test Build with Maven
        run: |
          mvn -B clean --file pom.xml
          mvn -B validate --file pom.xml
          mvn -B compile --file pom.xml
          mvn -B package --file pom.xml
          mvn -B clean --file pom.xml
      - name: Build and Publish Package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
