name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '8'
    - name: Maven
      run: |
        mvn -B clean --file pom.xml
        mvn -B validate --file pom.xml
        mvn -B compile --file pom.xml
        mvn -B package --file pom.xml
