name: Test
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Oracle JDK 8
      uses: oracle-actions/setup-java@v1    
      with:
        website: oracle.com
        release: 8
    - name: Maven
      run: |
        mvn -B clean --file pom.xml
        mvn -B validate --file pom.xml
        mvn -B compile --file pom.xml
        mvn -B package --file pom.xml
